name = "cloudflare-wordpress"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "wordpress-cloudflare"
database_id = "a061682a-515f-4fde-9b80-273632eb0e04"

[[kv_namespaces]]
binding = "HTML_CACHE"
id = "695adac89df4448e81b9ffc05f639491"

[vars]
PURGE_SECRET = "REPLACE_WITH_A_SECURE_KEY"
SYNC_SECRET_KEY = "Lui@63006021"
