name = "cloudflare-wordpress"
pages_build_output_dir = ".svelte-kit/cloudflare"

# 啟用 Node.js 兼容模式（修復 Error 1003）
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "wordpress-cloudflare"
database_id = "a061682a-515f-4fde-9b80-273632eb0e04"

[[kv_namespaces]]
binding = "HTML_CACHE"
id = "695adac89df4448e81b9ffc05f639491"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media-bucket"

# [vars] 臨時測試用 - 生產環境應該用 wrangler secret put
[vars]
SYNC_SECRET_KEY = "Lui@63006021"
PURGE_SECRET = "Lui@63006021"

